# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-12 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equiments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equ',
            name='serialNum',
            field=models.CharField(max_length=20),
        ),
    ]
