# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-17 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equiments', '0002_auto_20200312_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='equ',
            name='equ_type',
            field=models.CharField(default='zd001', max_length=30),
        ),
    ]
