# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-25 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equiments', '0003_equ_equ_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanName', models.CharField(max_length=20)),
                ('jobNum', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('equ_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='equ',
            name='equ_status',
            field=models.CharField(max_length=10),
        ),
    ]
