# Generated by Django 2.1.15 on 2020-05-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equiments', '0004_auto_20200325_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNum', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('equ_status', models.CharField(max_length=5)),
                ('desc', models.CharField(default=None, max_length=120)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.CharField(max_length=10)),
            ],
        ),
    ]
