# Generated by Django 2.1.15 on 2020-05-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equiments', '0005_repay'),
    ]

    operations = [
        migrations.AddField(
            model_name='equ',
            name='category',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='equ',
            name='equ_type',
            field=models.CharField(max_length=30),
        ),
    ]
