# Generated by Django 2.1.15 on 2020-05-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equiments', '0006_auto_20200518_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmsg',
            name='category',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
